// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void loadpage1_Animation(lv_obj_t * TargetObject, int delay);
void loadpage2_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(lv_obj_t * cont);
extern lv_obj_t * ui_Screen1;
void ui_event_Panel1(lv_event_t * e);
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_TimeLabel1;
extern lv_obj_t * ui_TimeLabel2;
extern lv_obj_t * ui_WeatherImage2;
extern lv_obj_t * ui_DataLabel2;
extern lv_obj_t * ui_StateBar;
extern lv_obj_t * ui_BuleLabel3;
extern lv_obj_t * ui_WifiLabel4;
void ui_event_Panel2(lv_event_t * e);
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_AppImage1;
extern lv_obj_t * ui_AppPanel3;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_2051629593);    // assets/雨.png
LV_IMG_DECLARE(ui_img_defaut_png);    // assets/defaut.png






void ui_init(lv_obj_t * cont);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
