// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(lv_obj_t * cont)
{
    ui_Screen1 = cont;
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 230);
    lv_obj_set_height(ui_Panel1, 120);
    lv_obj_set_x(ui_Panel1, -1);
    lv_obj_set_y(ui_Panel1, -95);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xF5EFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel1 = lv_label_create(ui_Panel1);
    ui_TimeLabel2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_TimeLabel1, 85);
    lv_obj_set_height(ui_TimeLabel1, 81);

    lv_obj_set_width(ui_TimeLabel2, 85);
    lv_obj_set_height(ui_TimeLabel2, 81);
    lv_obj_set_x(ui_TimeLabel1, -52);
    lv_obj_set_y(ui_TimeLabel1, 6);

    lv_obj_set_x(ui_TimeLabel2, -22);
    lv_obj_set_y(ui_TimeLabel2, 35);

    lv_obj_set_align(ui_TimeLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabel1, "12");
    lv_obj_set_style_text_font(ui_TimeLabel1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_align(ui_TimeLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabel2, "20");
    lv_obj_set_style_text_font(ui_TimeLabel2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherImage2 = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_WeatherImage2, &ui_img_2051629593);
    lv_obj_set_width(ui_WeatherImage2, 60);
    lv_obj_set_height(ui_WeatherImage2, 60);
    lv_obj_set_x(ui_WeatherImage2, 54);
    lv_obj_set_y(ui_WeatherImage2, -5);
    lv_obj_set_align(ui_WeatherImage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WeatherImage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_add_flag(ui_WeatherImage2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_WeatherImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DataLabel2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_DataLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DataLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DataLabel2, 50);
    lv_obj_set_y(ui_DataLabel2, 36);
    lv_obj_set_align(ui_DataLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DataLabel2, "Sat Mar 11");
    lv_obj_set_style_text_font(ui_DataLabel2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StateBar = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_StateBar, 238);
    lv_obj_set_height(ui_StateBar, 55);
    lv_obj_set_x(ui_StateBar, 2);
    lv_obj_set_y(ui_StateBar, -64);
    lv_obj_set_align(ui_StateBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StateBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BuleLabel3= lv_label_create(ui_StateBar);
    lv_label_set_text(ui_BuleLabel3,LV_SYMBOL_BLUETOOTH);
    lv_obj_set_width(ui_BuleLabel3, 15);
    lv_obj_set_height(ui_BuleLabel3, 15);
    lv_obj_set_x(ui_BuleLabel3, -69);
    lv_obj_set_y(ui_BuleLabel3, 12);
    lv_obj_set_align(ui_BuleLabel3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BuleLabel3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BuleLabel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiLabel4 = lv_label_create(ui_StateBar);
    lv_label_set_text(ui_WifiLabel4, LV_SYMBOL_WIFI);
    lv_obj_set_width(ui_WifiLabel4, 15);
    lv_obj_set_height(ui_WifiLabel4, 15);
    lv_obj_set_x(ui_WifiLabel4, -93);
    lv_obj_set_y(ui_WifiLabel4, 12);
    lv_obj_set_align(ui_WifiLabel4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiLabel4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiLabel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 230);
    lv_obj_set_height(ui_Panel2, 177);
    lv_obj_set_x(ui_Panel2, 2);
    lv_obj_set_y(ui_Panel2, 62);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xF5EFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AppImage1 = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_AppImage1, &ui_img_defaut_png);
    lv_obj_set_width(ui_AppImage1, 60);
    lv_obj_set_height(ui_AppImage1, 60);
    lv_obj_set_x(ui_AppImage1, -51);
    lv_obj_set_y(ui_AppImage1, 0);
    lv_obj_set_align(ui_AppImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AppImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_add_flag(ui_AppImage1,LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_AppImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AppPanel3 = lv_obj_create(ui_Panel2);
    lv_obj_set_width(ui_AppPanel3, 110);
    lv_obj_set_height(ui_AppPanel3, 168);
    lv_obj_set_x(ui_AppPanel3, 7);
    lv_obj_set_y(ui_AppPanel3, -1);
//    lv_obj_add_event_cb(ui_AppPanel3, scroll_end_event, LV_EVENT_SCROLL_END, NULL);
    lv_obj_set_style_pad_gap(ui_AppPanel3, 20, 0);
    lv_obj_set_align(ui_AppPanel3, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_AppPanel3,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_clip_corner(ui_AppPanel3, true, 0);
    lv_obj_set_scroll_dir(ui_AppPanel3, LV_DIR_VER);
    lv_obj_set_scroll_snap_y(ui_AppPanel3, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_scrollbar_mode(ui_AppPanel3, LV_SCROLLBAR_MODE_OFF);

    lv_obj_set_style_bg_color(ui_AppPanel3, lv_color_hex(0xF5EFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AppPanel3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AppPanel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AppPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AppPanel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AppPanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Panel1, ui_event_Panel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel2, ui_event_Panel2, LV_EVENT_ALL, NULL);

    lv_event_send(ui_Panel1,LV_EVENT_SCREEN_LOADED,NULL);
    lv_event_send(ui_Panel2,LV_EVENT_SCREEN_LOADED,NULL);

}
